version: '3.1'

services:
  mysql-container:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 918273
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: